name: CommunityMinecraftPlugin
main: io.github.communityminecraftplugin.communityminecraftplugin.Core
version: ${project.version}
description: Hello world!
commands:
  hacktoberfest:
    description: The Hacktoberfest command!
    usage: /hacktoberfest
  helloworld:
    description: Hello, world!
    usage: /helloworld
  fly:
    description: Fly around!
    usage: /fly (Optional <user>)
  getitem:
    description: Give a UsableItem to a player
    usage: /getitem <itemName> <Player>
  heal:
    description: /heal
    usage: /heal